version: "3"
networks:
  backend:
    driver: "bridge"
services:
  auth:
    container_name: auth
    # restart: always
    build: .
    ports:
      - "3010:3010"
    links:
      - mongo
    networks: 
      - backend
    env_file:
      - ${ENV_FILE}
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - backend
